Push to dockerhub on tag creation. Closes #59

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,6 +3,7 @@ name: CI/CD
 on:
   push:
     branches: [ "*" ]
+    tags: [ "*" ]
   workflow_dispatch:
 
 permissions:
@@ -59,21 +60,35 @@ jobs:
     - name: Build wheel
       run: poetry build --format wheel
     - name: Build Docker image
-      run: docker build -t 921216064263.dkr.ecr.eu-west-2.amazonaws.com/control-plane:$(echo $GITHUB_SHA | cut -c1-8) .
+      run: docker build -t control-plane:latest .
     - name: Install AWS CLI
-      if: github.ref == 'refs/heads/dev'
+      if: github.ref == 'refs/heads/master'
       run: |
         pip install --upgrade pip
         pip install awscli
     - name: Upload image to ECR
-      if: github.ref == 'refs/heads/dev'
+      if: github.ref == 'refs/heads/master'
       run: |
-        aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 921216064263.dkr.ecr.eu-west-2.amazonaws.com
-        docker push 921216064263.dkr.ecr.eu-west-2.amazonaws.com/control-plane:$(echo $GITHUB_SHA | cut -c1-8)
+        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
+        docker tag control-plane:latest $ECR_REGISTRY/$ECR_REPOSITORY:$(echo $GITHUB_SHA | cut -c1-8)
+        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$(echo $GITHUB_SHA | cut -c1-8)
       env:
+        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
+        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: 'eu-west-2'
+        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
+    - name: Upload image to Dockerhub
+      if: startsWith(github.ref, 'refs/tags/')
+      run: |
+        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
+        docker tag control-plane:latest $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:${{ github.ref_name }}
+        docker push $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:${{ github.ref_name }}
+      env:
+        DOCKERHUB_REGISTRY: ${{ secrets.DOCKERHUB_REGISTRY }}
+        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
+        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
 
   python-client:
     needs: control-plane
@@ -104,3 +119,14 @@ jobs:
         run: bash scripts/lint.sh
       - name: Build wheel
         run: poetry build --format wheel
+      - name: Upload wheel to PyPI
+        if: startsWith(github.ref, 'refs/tags/')
+        run: |
+          if [ ! -f dist/multinode-${{ github.ref_name }}-py3-none-any.whl ]; then
+              echo "Error: git tag is incompatible with wheel version number."
+              exit 1
+          fi
+          poetry config pypi-token.pypi $PYPI_TOKEN
+          poetry publish
+        env:
+          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
